spring:
  main:
    banner-mode: 'off'
  cloud:
    gateway:
      remove-non-proxy-headers:
          headers:
          - dummy
      discovery:
        locator:
          enabled: true
      routes:
      - id: agtms-web
        uri: lb://agtms-web
        predicates:
        - Path=/agtms/**
        filters:
        - StripPrefix=1

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000
            
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: basic
        
logging:
  level:
    net.saisimon: DEBUG
    
white:
  list:
    urls: /agtms/user/auth,/agtms/user/register