language: java
sudo: true

jdk:
  - openjdk8
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

install: true

script:
  - ./mvnw clean install
  - ./mvnw cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t a7c26320-35ba-43a4-bfbe-f98c40526e83
