#!/bin/sh

# 创建日志文件夹
mkdir -p data/eureka
mkdir -p data/web
mkdir -p data/zuul

# Maven 打包
bash mvnw clean install -DskipTests -Ddockerfile.skip=true
if [ $? -gt 0 ]; then
    echo "maven 构建失败."
    exit
fi

if [ $# -eq 0 ]; then
    arr=("eureka" "web" "zuul" "vue")
else
    c=0
    v=0
    for p in "$@"; do
        if [ "$p" == "eureka" ]; then
            arr[c]=$p
            c=$c+1
        elif [ "$p" == "web" ]; then
            arr[c]=$p
            c=$c+1
        elif [ "$p" == "zuul" ]; then
            arr[c]=$p
            c=$c+1
        elif [ "$p" == "vue" ]; then
            v=1
        else
            echo "未知参数，参数只支持:eureka、web、zuul、vue"
        fi
    done
    # agtms-vue 最后启动
    if [ $v -eq 1 ]; then
        arr[c]="vue"
    fi
fi

for i in "${arr[@]}"; do
    if [ "$i" == "eureka" ]; then
        # 启动 agtms-eureka
        if [ -f data/eureka/eureka.pid ]; then
            kill -9 `cat data/eureka/eureka.pid`
            rm data/eureka/eureka.pid
            echo "agtms-eureka 已停止."
        fi
        echo "agtms-eureka 启动中..."
        java -jar -Xms512m -Xmx512m -Xmn192m -Xss256k agtms-eureka/target/agtms-eureka.jar > data/eureka/logs/agtms-eureka.log 2>&1 &
        echo $! > data/eureka/eureka.pid
    elif [ "$i" == "web" ]; then
        # 启动 agtms-web
        if [ -f data/web/web.pid ]; then
            kill -9 `cat data/web/web.pid`
            rm data/web/web.pid
            echo "agtms-web 已停止."
        fi
        echo "agtms-web 启动中..."
        java -jar -Xms1g -Xmx1g -Xmn384m -Xss256k agtms-parent/agtms-web/target/agtms-web.jar > data/web/logs/agtms-web.log 2>&1 &
        echo $! > data/web/web.pid
    elif [ "$i" == "zuul" ]; then
        # 启动 agtms-zuul
        if [ -f data/zuul/zuul.pid ]; then
            kill -9 `cat data/zuul/zuul.pid`
            rm data/zuul/zuul.pid
            echo "agtms-zuul 已停止."
        fi
        echo "agtms-zuul 启动中..."
        java -jar -Xms512m -Xmx512m -Xmn192m -Xss256k agtms-zuul/target/agtms-zuul.jar > data/zuul/logs/agtms-zuul.log 2>&1 &
        echo $! > data/zuul/zuul.pid
    elif [ "$i" == "vue" ]; then
        # 启动 agtms-vue
        cd agtms-vue
        echo "agtms-vue 启动中..."
        npm install
        npm run serve
        cd ../
    fi
    sleep 10
    echo "agtms-$i 已启动."
done