#!/bin/sh

# 创建日志文件夹
mkdir -p data/logs

# Maven 打包
bash mvnw clean package
if [ $? -gt 0 ]; then
    echo "maven 构建失败."
    exit
fi

# 启动 agtms-eureka
if [ -f data/eureka.pid ]; then
    kill -9 `cat data/eureka.pid`
    rm data/eureka.pid
    echo "agtms-eureka 已停止."
fi
java -jar agtms-eureka/target/agtms-eureka.jar > data/logs/eureka.log 2>&1 &
echo $! > data/eureka.pid
echo "agtms-eureka 启动中..."
sleep 10
echo "agtms-eureka 已启动."

# 启动 agtms-web
if [ -f data/web.pid ]; then
    kill -9 `cat data/web.pid`
    rm data/web.pid
    echo "agtms-web 已停止."
fi
java -jar agtms-parent/agtms-web/target/agtms-web.jar > data/logs/web.log 2>&1 &
echo $! > data/web.pid
echo "agtms-web 启动中..."
sleep 10
echo "agtms-web 已启动."

# 启动 agtms-zuul
if [ -f data/zuul.pid ]; then
    kill -9 `cat data/zuul.pid`
    rm data/zuul.pid
    echo "agtms-zuul 已停止."
fi
java -jar agtms-zuul/target/agtms-zuul.jar > data/logs/zuul.log 2>&1 &
echo $! > data/zuul.pid
echo "agtms-zuul 启动中..."
sleep 10
echo "agtms-zuul 已启动."

# 启动 agtms-vue
cd agtms-vue
echo "agtms-vue 启动中..."
npm install
npm run serve
cd ../