#!/bin/sh

# 创建日志文件夹
mkdir -p data/web

# Maven 打包
bash mvnw clean install -DskipTests -Ddockerfile.skip=true
if [ $? -gt 0 ]; then
    echo "maven 构建失败."
    exit
fi

# 启动 agtms-web
if [ -f data/web/web.pid ]; then
    kill -9 `cat data/web/web.pid`
    rm data/web/web.pid
    echo "agtms-web 已停止."
fi
java -jar -Xms1g -Xmx1g -Xmn384m -Xss256k agtms-parent/agtms-web/target/agtms-web.jar > data/web/logs/agtms-web.log 2>&1 &
echo $! > data/web/web.pid
echo "agtms-web 启动中..."
sleep 10
echo "agtms-web 已启动."

# 启动 agtms-vue
cd agtms-vue
echo "agtms-vue 启动中..."
npm install
npm run serve
cd ../