spring:
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    show-sql: true
    generate-ddl: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 15000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: full