spring:
  main:
    bannerMode: 'off'
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
  jackson:
    default-property-inclusion: non_null
  jpa:
    showSql: true
    generateDdl: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 15000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: full

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: ${user.dir}/data/web/logs/agtms-web.log