spring:
  application:
    name: AGTMS-WEB
  mvc:
    dispatchOptionsRequest: true
  main:
    bannerMode: 'off'
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
  jpa:
    showSql: true
    generateDdl: true

server:
  port: 7892
  compression:
    enabled: true

white:
  list:
    urls: /user/auth
  prefix:
    urls: /image/res