spring:
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    show-sql: true
    generate-ddl: true
extra:
  class:
    path: /tmp/classes
  max-size:
    task: 5
    export: 65535
    import: 65535