version: 2

jobs:
  build:
    working_directory: ~/agtms
    docker:
      - image: circleci/openjdk:8-jdk
      - image: zookeeper
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
    steps:
      - checkout
      - run: echo "127.0.0.1 zookeeperserver" | sudo tee -a /etc/hosts
      - run: chmod +x mvnw
      - run: sudo curl --silent --show-error --location --fail --retry 3 --output /usr/bin/jq https://circle-downloads.s3.amazonaws.com/circleci-images/cache/linux-amd64/jq-latest
      - run: sudo chmod +x /usr/bin/jq
      - run: sudo jq --version
      - run: sudo apt-get install wget
      - restore_cache:
          keys:
            - agtms-{{ .Branch }}-{{ checksum "pom.xml" }}
            - agtms-{{ .Branch }}-
            - agtms-
      - run: ./mvnw clean install -Ddockerfile.skip=true --quiet
      - save_cache:
          paths:
            - ~/.m2
          key: agtms-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: bash <(curl -s https://codecov.io/bash)
      - run: LATEST_VERSION="$(curl -Ls https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)"
      - run: curl -Ls -o codacy-coverage-reporter-assembly.jar "https://dl.bintray.com/codacy/Binaries/${LATEST_VERSION}/codacy-coverage-reporter-assembly.jar"
      - run: java -jar codacy-coverage-reporter-assembly.jar report -l Java -r agtms-record/target/site/jacoco-aggregate/jacoco.xml