version: 2

jobs:
  build:
    working_directory: ~/agtms
    docker:
      - image: circleci/jdk8:0.1.1
      - image: zookeeper
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
    steps:
      - checkout
      - run: echo "127.0.0.1 zookeeperserver" | sudo tee -a /etc/hosts
      - run: chmod +x mvnw
      - run: sudo apt-get install jq wget
      - restore_cache:
          keys:
            - agtms-{{ .Branch }}-{{ checksum "pom.xml" }}
            - agtms-{{ .Branch }}-
            - agtms-
      - run: ./mvnw clean install -Ddockerfile.skip=true --quiet
      - save_cache:
          paths:
            - ~/.m2
          key: agtms-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: bash <(curl -s https://codecov.io/bash)
      - run: wget -O codacy-coverage-reporter-assembly.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("application/java-archive"))) | .[0].browser_download_url')
      - run: java -jar ./codacy-coverage-reporter-assembly.jar report -l Java -r agtms-record/target/site/jacoco-aggregate/jacoco.xml    