spring:
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

zuul:
  host:
    SocketTimeoutMillis: 10000
    ConnectTimeoutMillis: 10000
  routes:
    agtms:
      path: /agtms/**
      serviceId: AGTMS-WEB
      sensitiveHeaders: '*'
    web:
      path: /agtms-web/**
      serviceId: AGTMS-WEB

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 15000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: full

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: ${user.dir}/data/zuul/logs/agtms-zuul.log

white:
  list:
    urls: /agtms/user/auth,/agtms/task/main/download
  prefix:
    urls: /agtms/image/res