spring:
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      max-file-size: 10MB

zuul:
  host:
    SocketTimeoutMillis: 10000
    ConnectTimeoutMillis: 10000
  routes:
    agtms:
      path: /agtms/**
      serviceId: AGTMS-WEB
      sensitiveHeaders: '*'
    web:
      path: /agtms-web/**
      serviceId: AGTMS-WEB

white:
  list:
    urls: /agtms/user/auth,/agtms/user/register